# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56c7778aea24f127d1486007dedcc5c923d56f6ea3d41c63f7bceaa597316fdb466bce3ff1eefec4703d48ee3fdde93ffb37e697d077772987a665c3fe9aec0b

test:
  secret_key_base: 55a890ded7fab62520fc07c3d94a077cb3ba8fb25fb1035d1547d8b73d5074ef2beaaf2f513345c94d1d99272108887842b4adf129be9fcd8da193803fd22daa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
